version: '3.3'
services:
  web:
    command: './manage.py collectstatic --noinput && ./manage.py runserver 0.0.0.0:8000'
    environment:
      DEBUG: "false"

  webserver:
    command: [ nginx, '-g', 'daemon off;' ]
    environment:
      STATIC_LOCATION_PATTERN: '^/static/(.*)$$'

  webpack:
    command: yarn build
    environment:
      NODE_ENV: production
      PUBLIC_PATH: https://fiesta.localhost/static/

  dockerproxy:
    ports:
      - "80:80"
      - "443:443"

  # remove profiles so production env does have filled elastic search
  elastic:
    profiles: [ ]

  wikifetcher:
    profiles: [ ]
