version: '3.3'
services:
  web:
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fiesta/:/usr/src/app/
      - web_static_files:/usr/src/static
      - web_media_files:/usr/src/media
    expose:
      - 8000
    secrets:
      - .env
    build:
      context: .
      dockerfile: fiesta/Dockerfile
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=web.localhost
      - VIRTUAL_PORT=8000

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      - POSTGRES_USER=fiesta
      - POSTGRES_PASSWORD=fiesta
      - POSTGRES_DB=fiesta
      - TZ=Europe/Prague

  webserver:
    container_name: webserver
    build: ./nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    expose:
      - "80"
    volumes:
      - web_static_files:/static
      - web_media_files:/media
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=fiesta.localhost
      - VIRTUAL_PORT=80

  localproxy:
    container_name: localproxy
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

secrets:
  .env:
    file: ./.env

volumes:
  postgres_data:
  web_static_files:
  web_media_files:
