version: '3.3'
services:
  web:
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fiesta/:/usr/src/app/
      - web_static_files:/usr/src/static
      - web_media_files:/usr/src/media
      - webpack_build:/usr/src/build
    expose:
      - 8000
    env_file:
      - ./fiesta/.env.base
    secrets:
      - .env
    build:
      context: .
      dockerfile: fiesta/Dockerfile
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=web.localhost
      - VIRTUAL_PORT=8000

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      - POSTGRES_USER=fiesta
      - POSTGRES_PASSWORD=fiesta
      - POSTGRES_DB=fiesta
      - TZ=Europe/Prague

  webserver:
    container_name: webserver
    build: ./nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    expose:
      - 80
    volumes:
      - web_static_files:/static
      - web_media_files:/media
      - webpack_build:/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=fiesta.localhost
      - VIRTUAL_PORT=80

  localproxy:
    container_name: localproxy
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  webpack:
    build: ./webpack
    command: dev
    container_name: webpack
    expose:
      - 8003
    volumes:
      - ./webpack/:/usr/src/app
      - webpack_build:/usr/src/build
      # since tailwind need to access templates and all the stuff to dynamicaly strip classes
      # see more in webpack/tailwind.config.js
      - ./fiesta/:/usr/src/fiesta
    environment:
      - VIRTUAL_HOST=webpack.localhost
      - VIRTUAL_PORT=8003
      - BUILD_DIR=/usr/src/build
      - NODE_ENV=development
      - PUBLIC_PATH=https://webpack.localhost/static/


secrets:
  .env:
    file: ./.env

volumes:
  postgres_data:
  webpack_build:
  web_static_files:
  web_media_files:
