[tool.poetry]
name = "buena-fiesta"
version = "0.0.1"
description = "New generation of social network for helping international students - used by sections of Erasmus Student Network."
authors = ["ESN VUT BRNO"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0.1"
python-decouple = "^3.5"
psycopg2-binary = "^2.9.3"
django-debug-toolbar = "^3.2.4"
django-polymorphic = "^3.1.0"
django-extensions = "^3.1.5"
django-countries = "^7.2.1"
django-allauth = "^0.47.0"
django-webpack-loader = "^1.4.1"
django-click = "^2.3.0"
mysqlclient = "^2.1.0"
bcrypt = "^3.2.0"
django-htmx = "^1.8.0"
django-lifecycle = "^0.9.3"
django-allauth-cas = { git = "https://github.com/thejoeejoee/django-allauth-cas.git", branch = "master" }

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pydotplus = "^2.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.flake8]
max-line-length = 120
extend-ignore = "C408,"
max-complexity = 10

[tool.isort]
profile = 'black'
lines_between_types = 1
combine_as_imports = true
line_length = 120
known_first_party = ["fiesta", "apps"]
known_local_folder = ["apps"]

[tool.black]
exclude = '''
(
  /(
    | .+/migrations
  )/
)
'''
