[tool.poetry]
name = "buena-fiesta"
version = "0.0.1"
description = "New generation of social network for helping international students - used by sections of Erasmus Student Network."
authors = ["ESN VUT BRNO"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0.1"
python-decouple = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
