[tool.poetry]
name = "buena-fiesta"
version = "0.0.1"
description = "New generation of social network for helping international students - used by sections of Erasmus Student Network."
authors = ["ESN VUT BRNO"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0.1"
python-decouple = "^3.5"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pylint-django = "^2.5.0"
pylint = "^2.12.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.flake8]
max-line-length = 120
# extend-ignore = "E203,"
max-complexity = 10

[tool.isort]
profile = 'black'
lines_between_types = 1
combine_as_imports = true
line_length = 120
known_first_party = ["fiesta", "apps"]
